name: MinecraftSkills
main: me.MinecraftSkills.main.main
version: 1.0
author: Mauchel1
api-version: 1.14
commands:
  skill_mining:
    description: Zeigt die Bergbau Fertigkeiten
    usage: /skill_mining
  skill_agility:
    description: Zeigt die Agility Fertigkeiten
    usage: /skill_agility