name: MinecraftSkills
main: me.MinecraftSkills.main.main
version: 1.0
author: Mauchel1
api-version: 1.14
commands:
  skill:
    description: Zeigt die Skill CommandSachen
    usage: /skill
  skill_mining:
    description: Zeigt die Bergbau Fertigkeiten
    usage: /skill_mining
  skill_agility:
    description: Zeigt die Agility Fertigkeiten
    usage: /skill_agility
  skill_alchemy:
    description: Zeigt die Alchemie Fertigkeiten
    usage: /skill_alchemy
  skill_farming:
    description: Zeigt die Farm Fertigkeiten
    usage: /skill_farming
  skill_fishing:
    description: Zeigt die Fischer Fertigkeiten
    usage: /skill_fishing
  skill_woodcutting:
    description: Zeigt die Woodcutting Fertigkeiten
    usage: /skill_woodcutting
  skill_digging:
    description: Zeigt die Grabungs Fertigkeiten
    usage: /skill_digging
  skill_sword:
    description: Zeigt die Schwert Fertigkeiten
    usage: /skill_sword
  skill_axe:
    description: Zeigt die Axt Fertigkeiten
    usage: /skill_axe
  skill_fist:
    description: Zeigt die Faust Fertigkeiten
    usage: /skill_fist
  skill_bow:
    description: Zeigt die Bogen Fertigkeiten
    usage: /skill_bow
  skill_crossbow:
    description: Zeigt die Armbrust Fertigkeiten
    usage: /skill_crossbow