name: MinecraftSkills
main: me.MinecraftSkills.main.main
version: 1.0
author: Mauchel1
api-version: 1.14
commands:
  skill_mining:
    description: Zeigt die Bergbau Fertigkeiten
    usage: /skill_mining
  skill_agility:
    description: Zeigt die Agility Fertigkeiten
    usage: /skill_agility
  skill_alchemy:
    description: Zeigt die Alchemie Fertigkeiten
    usage: /skill_alchemy
  skill_farming:
    description: Zeigt die Farm Fertigkeiten
    usage: /skill_farming
  skill_fishing:
    description: Zeigt die Fischer Fertigkeiten
    usage: /skill_fishing
  skill_woodcutting:
    description: Zeigt die Woodcutting Fertigkeiten
    usage: /skill_woodcutting
    