Ability:
  Woodcutting:
    SuperAxe:
      activationLevel: 20.0
      # maxBlockBreakNumber: 20.0
      maxBlockNumberLvlMultiplyer: 0.5
      # maxBlockBreakNumber: 500.0
      timeStaysReady: 7.0
      maxTimeToNextUse: 180.0
      minTimeToNextUse: 10.0
      timeReducedPerLevel: 0.5
  Mining:
    DoubleDrop:
      chanceIncreasePerLevelInPercent: 0.1
  Farming:
    DoubleDrop:
      chanceIncreasePerLevelInPercent: 0.1
    GreenThumb:
      chanceIncreasePerLevelInPercent: 0.1
      